# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Locke Data"
license = "MIT"
licenselink = "https://github.com/lockedata/hugo-lockedata"
description = "The theme for Locke Data"
homepage = ""
tags = []
features = []
min_version = "0.18"

[author]
  name = "Stephanie Locke"
  homepage = "https://itsalocke.com"

# If porting an existing theme
[original]
  name = "Agency"
  homepage = "http://themes.gohugo.io/theme/agency/"
  repo = "https://github.com/digitalcraftsman/hugo-agency-theme"
